packages:
  - apps/*
  - libs/*
  - packages/*
  - tools/*

catalog:
  "@clerk/nextjs": 6.36.8
  "@dopplerhq/node-sdk": 1.3.0
  "@j5/component-library": workspace:*
  "@playwright/test": 1.57.0
  "@radix-ui/react-separator": 1.1.8
  "@sentry/nextjs": 10.34.0
  "@storybook/nextjs-vite": 10.1.11
  "@t3-oss/env-core": 0.13.10
  "@t3-oss/env-nextjs": 0.13.10
  "@tailwindcss/postcss": 4.1.18
  "@tailwindcss/vite": 4.1.18
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  convex: 1.31.5
  convex-helpers: 0.1.111
  dayjs: 1.11.19
  dotenv: 17.2.3
  eslint-plugin-storybook: 10.1.11
  geist: 1.5.1
  lucide-react: 0.562.0
  neverthrow: 8.2.0
  next: 16.1.3
  postcss: 8.5.6
  posthog-js: 1.328.0
  react: 19.2.3
  react-dom: 19.2.3
  simple-git: 3.30.0
  storybook: 10.1.11
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7
  tslib: 2.8.1
  vite: 7.3.1
  vite-tsconfig-paths: 6.0.4
  vitest: 4.0.17
  zod: 3.25.76

onlyBuiltDependencies:
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - unrs-resolver
