packages:
  - "apps/*"
  - "libs/*"
  - "packages/*"
  - "tools/*"
onlyBuiltDependencies:
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "core-js"
  - "core-js-pure"
  - "esbuild"
  - "nx"
  - "sharp"
  - "unrs-resolver"
