packages:
  - apps/*
  - libs/*
  - packages/*
  - tools/*

catalog:
  '@clerk/nextjs': 6.36.8
  '@j5/component-library': workspace:*
  '@storybook/nextjs-vite': 10.1.11
  '@t3-oss/env-core': 0.13.10
  '@t3-oss/env-nextjs': 0.13.10
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/vite': 4.1.18
  convex: 1.31.5
  convex-helpers: 0.1.111
  next: 16.1.3
  postcss: 8.5.6
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: 4.1.18
  vite-tsconfig-paths: 6.0.4
  vitest: 4.0.17
  zod: 3.25.76

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - unrs-resolver
