packages:
  - apps/*
  - packages/*
  - libs/*
  - libs
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - sharp
  - unrs-resolver
